version: 2.1

orbs:
  gcp-gcr: circleci/gcp-gcr@0.11.0

jobs:
  build_and_test:
    docker:
      - image: circleci/golang:1.15

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    #### TEMPLATE_NOTE: go expects specific checkout path representing url
    #### expecting it in the form of
    ####   /go/src/github.com/circleci/go-tool
    ####   /go/src/bitbucket.org/circleci/go-tool
    working_directory: /go/src/github.com/sherry-tay/personal-finance
    
    environment: # environment variables for the build itself
      TEST_RESULTS: /tmp/test-results

    steps:
      - checkout

      - restore_cache:
          keys:
            - go-mod-v4-{{ checksum "go.sum" }}

      - run: go get -v -t -d ./...

      - save_cache:
          key: go-mod-v4-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"

      - run: mkdir -p $TEST_RESULTS
      
      - run: gotestsum --junitfile ${TEST_RESULTS}/gotestsum-report.xml -- ./...

      - store_artifacts:
          path: /tmp/test-results
          destination: raw-test-output

      - store_test_results:
          path: /tmp/test-results

  deploy:
    docker:
      - image: hashicorp/terraform

    working_directory: /go/src/github.com/sherry-tay/personal-finance

    steps:
      - checkout
      - run: cd deploy && terraform init -backend-config="credentials=$GCLOUD_SERVICE_KEY"
      - run: >-
          cd deploy && terraform apply -auto-approve
          -var "key_file=$GCLOUD_SERVICE_KEY"
          -var "project=$GOOGLE_PROJECT_ID"
          -var "image=us.gcr.io/$GOOGLE_PROJECT_ID/personal-finance:$CIRCLE_WORKFLOW_ID"
          -var "telegram_bot_token=$TELEGRAM_BOT_TOKEN"
          -var "telegram_bot_authorised_username=$AUTHORIZED_USER"

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - build_and_test
      - approve_docker_push_deploy:
          type: approval
          requires:
            - build_and_test
          filters:
            branches:
              only: master
      - gcp-gcr/build-and-push-image:
          image: personal-finance
          registry-url: us.gcr.io
          tag: $CIRCLE_WORKFLOW_ID
          requires:
            - approve_docker_push_deploy
      - deploy:
          requires:
            - gcp-gcr/build-and-push-image
